- brand: Music Man
  brand_aliases: [MM, MusicMan, musicman, EBMM, Ernie Ball]
  models:
    - name: Axis
      aliases: []
      search: true
    - name: Luke
      aliases: [Lukather]
      search: true
- brand: Fender
  brand_aliases: []
  models:
    - name: Stratocaster Custom Shop
      aliases: [Stratocaster CS, Strat CS, Strat Custom Shop]
      search: true